### ISSUE TITLE
Uncaught TypeError during autocomplete

### ISSUE THREAD

**Issue by carlsverre** [1995eaton/chromium-vim#537] opened 2017-04-26 04:40 UTC
I am getting the following error when I use autocomplete with a form that is backed by a React.js app that I am developing:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at KeyListener.eventToCode (keys.js:134)
    at keys.js:147
```

The issue is here: https://github.com/1995eaton/chromium-vim/blob/master/content_scripts/keys.js#L134
It seems that in my case `event.key` is undefined.  The full event object looks something like this:

```
Event
bubbles : true
cancelBubble : false
cancelable : false
composed : false
currentTarget : Window
defaultPrevented : false
eventPhase : 1
isTrusted : true
path : Array[18]
returnValue : true
srcElement : input#cardholderName
target : input#cardholderName
timeStamp : 148754.77500000002
type : "keydown"
```

**Comment by raymond-w-ko** [comment] 2017-07-10 16:50
I am also getting this error in a login form when using React.js. Conditions are exactly described by parent.

**Comment by 1995eaton** [comment] 2017-07-10 17:26
I am somewhat unfamiliar with React.js. Can anyone point me to a website/demo page where this bug occurs?

**Comment by raymond-w-ko** [comment] 2017-07-10 17:29
If you have a Netflix account, the Netflix sign in form also triggers this error.

**Comment by 1995eaton** [comment] 2017-07-11 02:59
I'm unable to reproduce this issue on the Netflix sign in form. Which version of Chrome are you all using?

**Comment by raymond-w-ko** [comment] 2017-07-11 15:06
Version 59.0.3071.115 (Official Build) (64-bit)

Steps to reproduce
1. Make sure you are logged out.
2. Go to https://www.netflix.com
3. Open the Chrome Inspector, go to Console.
4. Click on the "Sign In" button in the upper right.
5. Your email + password should appear in the input fields due to auto-complete, and they should be yellow-ish.
6. Get the following stack trace:
```
keys.js:134 Uncaught TypeError: Cannot read property 'length' of undefined
    at KeyListener.eventToCode (keys.js:134)
    at keys.js:147
KeyListener.eventToCode @ keys.js:134
(anonymous) @ keys.js:147
keys.js:134 Uncaught TypeError: Cannot read property 'length' of undefined
    at KeyListener.eventToCode (keys.js:134)
    at keys.js:147
KeyListener.eventToCode @ keys.js:134
(anonymous) @ keys.js:147
keys.js:134 Uncaught TypeError: Cannot read property 'length' of undefined
    at KeyListener.eventToCode (keys.js:134)
    at keys.js:147
```

**Comment by 1995eaton** [comment] 2017-07-19 16:44
Seems to be fixed now. I could only reproduce this on Chrome 59, not 58.

**Closed** 2017-07-19 16:44 UTC
