### ISSUE TITLE
Scroll inside scrollable div

### ISSUE THREAD

**Issue by helixbass** [1995eaton/chromium-vim#193] opened 2014-12-27 01:55 UTC
Just switched from Vimium as cVim looks to be much more powerful/flexible, but this is one thing that I'm missing that Vimium supports: after having clicked inside a scrollable container, Vimium lets me use eg `j`/`k` to scroll the container similar to how at that point the browser lets me use Space/arrow keys. cVim doesn't seem to support that behavior?

**Comment by 1995eaton** [comment] 2015-01-15 17:11
Duplicate of #174. Still working on this one

**Closed by 1995eaton** 2015-01-15 17:11 UTC
