### ISSUE TITLE
Map to existing Chrome shortcuts

### ISSUE THREAD

**Issue by phlundblom** [1995eaton/chromium-vim#454] opened 2016-07-05 06:53 UTC
Not sure what I'm doing wrong but I just can't get any custom key mappings in cVim to override existing built-in mappings in Chrome. For example

```
map <C-f> scrollPageDown
map <C-b> scrollPageUp
map <C-o> goBack
map <C-i> goForward
```

Doesn't get me the expected vim (and vimperator) bindings for scrolling one page up or down or moving around in history. CTRL-f brings up the Chrome Find popup, CTRL-o the Chrome Open window. CTRL-b doesn't result in anything at all.

Other mappings for non-CTRL bindings works like a charm. What am I missing?

Chrome version 51.0.2704.106 (Official Build) (64-bit) on Linux.

**Comment by 1995eaton** [comment] 2016-07-08 03:28
Does mapping the shortcuts through the command line work?
For example, typing `:map <C-f> scrollPageDown` in normal mode.

**Comment by phlundblom** [comment] 2016-07-08 05:53
Unfortunately not :( Still just get the Find popup in the upper right corner.

**Comment by rosshadden** [comment] 2016-07-20 22:24
I have the same issue with all of these:

```vim
map <C-e> scrollDown
map <C-y> scrollUp
map <C-d> scrollPageDown
map <C-u> scrollPageUp
map <C-f> scrollFullPageDown
map <C-b> scrollFullPageUp
```

**Comment by 1995eaton** [comment] 2016-07-26 14:04
@phlundblom @rosshadden Have these keys worked in the past for you guys?

**Comment by rosshadden** [comment] 2016-07-26 14:49
@1995eaton Yes.  I'm not opposed to doing a git-bisect to figure out where it broke, though it is entirely possible that a chrome/ium change broke it.  Maybe that's even more likely.

I use Chrome 51.  It's worth noting that this problem spans two computers for me.  At first it was just one of them, but a week or so later the other got it as well.  Almost certainly because either Chrome or chromium-vim updated.  Hard to tell which.

**Comment by 1995eaton** [comment] 2016-07-26 15:01
I think I know where it broke. Try changing the `HAS_EVENT_KEY_SUPPORT` variable at https://github.com/1995eaton/chromium-vim/blob/master/content_scripts/keys.js#L5 to false.

**Comment by rosshadden** [comment] 2016-07-26 15:08
When I change it, Chrome disables the plugin and says "This extension may have been corrupted."  I cannot re-enable it, just "repair" it, which wipes the changes and config.

Ideas?

**Comment by 1995eaton** [comment] 2016-07-26 15:10
Are you loading cVim via the Chrome store? Try using the GitHub version.

**Comment by rosshadden** [comment] 2016-07-26 15:30
Unfortunately, changing `HAS_EVENT_KEY_SUPPORT` did not solve the issue.  `<c-f>` still brings up the browser's Find dialog, `<c-b>` still creates a bookmark, etc.

**Comment by rosshadden** [comment] 2016-08-11 14:38
It's worth noting that this happens to me in both Chrome (52) and Vivaldi.

Also, to be clear, this only started happening to me about a month ago.  Before then I had used cvim for a couple of years with mapping to these keys working perfectly.

**Comment by dumblob** [comment] 2016-09-13 14:04
I can confirm this issue. I would also like to unmap/remap the default Chromium (53.0.2785.101 64-bit) bindings.

**Comment by rosshadden** [comment] 2016-11-08 03:40
Any updates on this?  Is it working for anyone, or are most people just not trying to map these keys?

**Comment by rosshadden** [comment] 2016-11-10 16:44
Omg, I just figured it out!  It's related to keyboard layout!

Okay, I use dvorak.  Given my mappings above, if I hit the physical qwerty key itself, the mappings actually work.

Now, you might say "you dvorak/colemak/whatever people and your stupid keys", but it's actually not even close to that simple.  This is the first time in the 8 years I have been using linux+dvorak that a program has _ever_ had this sort of issue.  And this is only the `ctrl` keys---normal keys work as expected.

Anyway, I bet this is a chromium bug and has nothing to do with chromium-vim.  I said above that this used to all work fine for me, and that is true.  Thus I bet some change in the last year or so to chromium bjorked it.

@phlundblom, @dumblob:  Do either of you use a non-qwerty keyboard layout?

**Comment by rosshadden** [comment] 2016-11-10 16:57
Found it:  https://bugs.chromium.org/p/chromium/issues/detail?id=633838

This is definitely my issue.  If true for @phlundblom, we can close.

**Comment by phlundblom** [comment] 2016-11-10 19:35
Ehum, I'm also a DVORAK (with modifications) user... Haven't run into those kind of problems since I messed with custom layouts in Windoze...

**Comment by rosshadden** [comment] 2016-11-10 19:49
Awesome. Well, I think you should close the issue (and subscribe to the chromium one I mentioned).

**Closed** 2016-11-10 20:13 UTC

**Comment by rosshadden** [comment] 2016-11-11 15:45
By the way, @phlundblom, I ended up mapping things to the key that would be qwerty:

```
map <C-d> scrollDown
map <C-t> scrollUp
map <C-h> scrollPageDown
map <C-f> scrollPageUp
map <C-y> scrollFullPageDown
map <C-n> scrollFullPageUp
```

instead of `e`, `y`, `d`, `u`, `f`, and `b`, respectively.  It works well until they fix it in chromium.
